### ISSUE TITLE
Botsing problem with some examples

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/botsing#10]
#### Characteristics
- **Issue Type**: possible bug / misuse
- **Reproducibility**: always
- **Tool/Service/Component**: Botsing
- **Execution Environment**: Linux 
- **Reporter**: Ricardo Tejada <ricardo.tejada.external@atos.net>

#### Description
Botsing fails with a null pointer exception when using it on the given examples

![botsingexperiment](https://user-images.githubusercontent.com/36235771/46423483-2815c480-c726-11e8-89e3-d0759a9bd8c4.png)

![botsingexperimenttrace](https://user-images.githubusercontent.com/36235771/46423488-2c41e200-c726-11e8-923a-bdd3a9a24804.png)

#### Steps to reproduce
Execute botsing on the given example as shown in description

#### Files

Examples

[ExceptionsForBotsing.zip](https://github.com/STAMP-project/botsing/files/2442738/ExceptionsForBotsing.zip)

**Comment by pderakhshanfar** [comment]
Dear @RicardoTej, I can not reproduce this stack trace in my system. Although, Botsing cannot achieve to the crash reproduction in this frame either, because it can not find a public method which calls the target method. Can you please send me the source code of `null_pointer_example.jar`?

**Comment by RicardoTej** [comment]
Good morning : 

You are right it was a visibility problem, I changed the visibility of the private methods to public and now it works fine.

Thank you.
