### ISSUE TITLE
Maven log4j lib incompatibility with checkstyle

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#13]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: if maven is configured to use log4j
- **Severity**: minor
- **Tool/Service/Component**: botsing-reproduction 0.0.1-SNAPSHOT
- **Execution Environment**: All
- **Reporter**: Luca Andreatta luca.andreatta@eng.it

#### Description

If I try to compile botsing-reproduction and Maven is configured to use log4j I get a NoSuchMethodError exception:

`16:02:39.869 [main] ERROR o.a.m.c.MavenCli - Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle (default) on project botsing-reproduction: Execution default of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle: java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V`

#### Steps to reproduce

Configure Maven to use log4j and run mvn install inside botsing-reproduction

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by luandrea** [comment]
The solution will be to add this to pom.xml inide plugins:
```
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>2.17</version>
				<dependencies>
					<dependency>
						<groupId>org.slf4j</groupId>
						<artifactId>jcl-over-slf4j</artifactId>
						<version>1.7.5</version>
					</dependency>
				</dependencies>
			</plugin>
```

**Comment by xdevroey** [comment]
HI! Does updating checkstyle plugin version in the [main pom](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/pom.xml#L78) to [version 3.0.0](https://maven.apache.org/plugins/maven-checkstyle-plugin/) solve the issue?
