### ISSUE TITLE
No available documentation (user guide) to use Botsing. Please, provide CLI documentation, as available for DSpot or Descartes

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/botsing#15]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: always
- **Severity**:  major
- **Tool/Service/Component**: Botsing
- **Execution Environment**: All OS (Windows, Linux)
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
Botsing [readme.md](https://github.com/STAMP-project/botsing/blob/master/README.md) does not provide any documentation that describes:

- how to get Botsing software
- how to use Botsing in the CLI (or another client)
- how to configure Botsing
- examples of usage

Without this information is really difficult to start using Botsing and succeed on making it work. We need to go through the spare examples (Evocrash demo) or responses to some issues.

Meantime you provide this information, I will try to use the Eclipse Botsing [plugin](https://github.com/STAMP-project/stamp-ide/blob/master/README_Botsing.md), but I would like rather to use the CLI in order to clearly identify issues related to Botsing itself and not to client wrappers (i.e. Eclipse plugin).

#### Steps to reproduce
N/A
#### Other files and URLs
N/A
#### Relationships
N/A
#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by xdevroey** [comment]
Hi @jesus-gorronogoitia,

The README file (https://github.com/STAMP-project/botsing/blob/master/README.md) has been updated. A release is available at https://github.com/STAMP-project/botsing/releases/tag/botsing-1.0.0 with the standalone jar file (it contains all dependencies) to run Botsing. 

Best,

Xavier

**Comment by luandrea** [comment]
This issue is connected to #5

**Comment by xdevroey** [comment]
The list includes, on user side:
- [ ] how to get Botsing software
- [ ] how to use Botsing in the CLI
- [ ] how to use Botsing from Maven
- [ ] how to configure Botsing
- [ ] a tutorial or an example, maybe this could be in some other page and have here only a link to it
link to the stamp site

On the developer side:
- [ ] description of the project and modules
- [ ] how to compile and package it with prerequisites

Other:
- [ ] authors
- [ ] license note
