### ISSUE TITLE
Add integration in JIRA/GitHub

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/botsing#18]
We would find the following scenario very interesting for XWiki:
* A user logs an issue in the XWiki issue tracker (JIRA) with a stack trace
* Automatically a process is started (JIRA integration) which executes Botsing on the extracted stack trace
* If successful to reproduce, a comment with the test is added to the JIRA issue and a GitHub PR is opened with a regression test.

**Comment by xdevroey** [comment]
Hi @vmassol,

Interesting idea indeed! We have taught about that kind of use cases with @spookyvale but we would also need input from other UC providers to see if they have the same kind of requirements. Any comment/idea about this @ltboye, @MaelAudren, @jesus-gorronogoitia, @assadOW2?

**Comment by luandrea** [comment]
It's not a problem to develop a listener plugin in Jira that is triggered from some user action. What we should clarify, after the requirements from UC providers, will be the architecture of the solution.
In my opinion the jira listener should call Botsing through a service and then store the tests directly in github.

**Comment by jesus-gorronogoitia** [comment]
Hi, 
From a pure industrial point of view this requirement sound quite relevant. However, we are currently not using JIRA in our research department, but mostly a Gitlab tracker (or even other trackers like GitHub) so this feature based on JIRA could not be adopted/tested by us. Nonetheless, the idea is great and implementing support for JIRA sounds relevant.

**Comment by MaelAudren** [comment]
Hi,
I have the same feeling as Yosu, in Activeeon we are not using Jira. It would be better for use to have a jenkins plugin that ping github to get new issues and create pull request when there are stacktraces. However I don't know if it is possible to develop such plugin.

**Comment by vmassol** [comment]
Ok so far we've listed 3 issue trackers:
* github issues
* jira
* gitlab issues

**Comment by xdevroey** [comment]
For the record: as decided in Nice, Engineering will develop a plugin for the GitHub issue tracker for now.

**Comment by luandrea** [comment]
The botsing-github-app can be found here:

- https://github.com/STAMP-project/botsing-github-app
