### ISSUE TITLE
Decrease logging level for messages not relevant to normal usage

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/botsing#20]
#### Characteristics
- **Issue Type**: bug
- **Severity**: minor
- **Reporter**: @mbenguig

#### Description

Some logs are not required for a default utilization and could be enabled at a higher log level. This latter could be set from a dedicated property file.

**Comment by pderakhshanfar** [comment]
This issue is addressed in commits: 9906fb7 and 705353e.
Also, you can manage different modules log level in the [configuration file](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/main/resources/logback.xml).
