### ISSUE TITLE
The generated test should not contain a try-catch block

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/botsing#22]
#### Characteristics
- **Issue Type**: feature
- **Severity**: minor
- **Reporter**: @monperrus 

#### Description

The generated test should not contain a try-catch block because it is expected that a JUnit reproducing a crash fails.

**Comment by pderakhshanfar** [comment]
For this issue, you can pass `-Dcatch_undeclared_exceptions=FALSE` to Botsing as an input parameter.

**Comment by xdevroey** [comment]
Ok, I'll set it to false by default
