### ISSUE TITLE
Botsing not available on maven

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/botsing#24]
#### Characteristics
- **Issue Type**: [feature]
- **Severity**: [feature]

#### Description
It would be great for the plugins development to have Botsing available on maven repository.
Here is stamp-project maven repository where Botsing is missing: https://mvnrepository.com/search?q=eu.stamp-project

**Comment by xdevroey** [comment]
Here you go: https://search.maven.org/artifact/eu.stamp-project/botsing-reproduction/1.0.1/jar :-)

**Comment by MaelAudren** [comment]
It's working well, thanks a lot.
