### ISSUE TITLE
Add Maven parameters

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/botsing#30]
#### Characteristics
- **Issue Type**: feature
- **Tool/Service/Component**: botsing-1.0.2
- **Reporter**: @xdevroey, @pderakhshanfar, @luandrea 

#### Description

The Botsing Maven plugin shall have the following parameters:
- [x] `project_cp` the project dependencies with a default value set to the Maven project classpath.
- [x] `crash_log` the log file with the stack trace to consider.
- [x] `target_frame` the target frame. 

Other parameters from the [default configuration file](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/main/resources/config.properties) shall be:
- [ ] `population` the size of the population that evolves during the search with a default value of 100
- [ ] `search_budget` the search budget in seconds with a default value of 1800
- [ ] `global_timeout` the global timeout in seconds, after which the execution stops if the search is stuck with a default value of 1800 (the timeout is only reached if the search does not improve after 1800 seconds)
- [ ] `test_dir` the directory where the tests are generated with a default value of `crashreproduction-tests`
- [ ] `random_seed` the seed used to initialize the random number generator. This value allows to have deterministic behavior and should be set when performing evaluations

For those parameters, the [Botsing class](https://github.com/STAMP-project/botsing/blob/99293eec7552873cca296f9d225c9119dda6d887/botsing-reproduction/src/main/java/eu/stamp/botsing/Botsing.java#L60) uses a `-Dproperty_name=value` syntax (for instance, `-Dpopulation=100`). The Maven plugin shall follow the same syntax when calling the [Botsing.parseCommandLine](https://github.com/STAMP-project/botsing/blob/99293eec7552873cca296f9d225c9119dda6d887/botsing-reproduction/src/main/java/eu/stamp/botsing/Botsing.java#L45) method. 

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by luandrea** [comment]
All this parameters has been added in botsing-maven 1.0.5-SNAPSHOT
