### ISSUE TITLE
Add shading for Botsing dependencies

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/botsing#31]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: random
- **Severity**: major
- **Tool/Service/Component**: botsing-1.0.2
- **Reporter**: @MaelAudren @luandrea @xdevroey @pderakhshanfar 

#### Description
The dependencies of Botsing interferes with the classpath provided by the user if the classes are part of the dependencies themselves. This causes Botsing to consider the wrong class for instrumentation before starting the evolution+generation processes.

Shading Botsing dependencies should resolve that issue.  See [EvoSuite shading](https://github.com/EvoSuite/evosuite/blob/c332e55fcd4e7fe82c43fcae97698436ea06d67c/pom.xml#L747) for an example and list of classes. 

#### Steps to reproduce
- mkdir STAMP-project
- cd STAMP-project
- git clone https://github.com/apache/commons-collections
- cd commons-collections
- git checkout collections-4.0
- wget https://github.com/STAMP-project/EvoCrash-demo/raw/master/Demo/src/resources/logs/ACC/ACC-474/ACC-474.log
- mvn package -DskipTests
- mvn eu.stamp-project:botsing-maven:botsing -Dcrash_log=ACC-474.log -Dtarget_frame=2

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by pderakhshanfar** [comment]
Fixed in commit 636be06

**Comment by MaelAudren** [comment]
@pderakhshanfar @xdevroey I upgraded from version 1.0.1 to 1.0.3 and the bug fix is working well. Thanks a lot.
