### ISSUE TITLE
Crash with Maven 3.3.9

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#32]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: sometimes
- **Severity**: major
- **Tool/Service/Component**: Botsing Maven Plugin 1.0.1
- **Execution Environment**: All
- **Reporter**: Luca Andreatta <luca.andreatta@eng.it>

#### Description
If you run Botsing Maven Plugin with Maven 3.3.9, it doesn't work. Also using JDK 11 will not work.

#### Steps to reproduce

1. STAMP-project
2. cd STAMP-project
3. git clone https://github.com/apache/commons-collections
4. cd commons-collections
5. git checkout collections-4.0
6. wget https://github.com/STAMP-project/EvoCrash-demo/raw/master/Demo/src/resources/logs/ACC/ACC-474/ACC-474.log
7. docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn eu.stamp-project:botsing-maven:botsing -Dcrash_log=ACC-474.log -Dtarget_frame=2

You can run with different configurations changing the last step like this:

- docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.0-jdk-8 mvn eu.stamp-project:botsing-maven:botsing -Dcrash_log=ACC-474.log -Dtarget_frame=2

Take a look at https://hub.docker.com/_/maven/ for others configurations.

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
Ciao @luandrea Is this an issue for Botsing Eclipse plugin or for Botsing? The Botsing Eclipse plugin is not using Maven for executing Botsing, but direclty Botsing as a Java application (using its jar).

**Comment by luandrea** [comment]
Hola @jesus-gorronogoitia! This is an issue for Maven Botsing plugin only, so there is no problem for Botsing itself, not either for Botsing Eclipse plugin at least for Maven version.

**Comment by jesus-gorronogoitia** [comment]
Ciao @luandrea my fault, I misread the description and for any weird reason (I read plugin) I though, it referred to the Eclipse plugin. Ignore my comments.

**Comment by luandrea** [comment]
botsing-maven requires Maven 3.5.4+
