### ISSUE TITLE
Change the log level in maven plugin 

### ISSUE THREAD

**Issue by pderakhshanfar** [STAMP-project/botsing#40]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always

#### Description
We have a configuration file for Botsing and Evosuite logging level [here](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/main/resources/logback.xml). The botsing jar file follows this configuration. However, the Botsing maven plugin does not.

**Comment by luandrea** [comment]
Maven, by default uses the SLF4J API for logging combined with the SLF4J Simple implementation and the default log level is set to info for all but in that way there is a lot of log at info level by classes under org.evosuite package.
A simple solution is to set the logging level for org.evosuite to off in the simplelogger.properties file of Maven (for me it is /usr/share/maven/conf/logging/simplelogger.properties) adding this line:
`org.slf4j.simpleLogger.log.org.evosuite=off`

**Comment by luandrea** [comment]
I don't like to put something specific of EvoSuite in a general Maven configuration file, so the alternative is to add this parameter when the plugin is invoked.
The parameters to add are:
- -Dorg.slf4j.simpleLogger.log.org.evosuite=off
- -Dorg.slf4j.simpleLogger.showLogName=true
The first one is to exclude org.evosuite packages, the second one is to show the class name and can be optional.

The resulting command will be something like that:
`mvn eu.stamp-project:botsing-maven:botsing -Dcrash_log=LANG-9b.log -Dtarget_frame=2 -Dorg.slf4j.simpleLogger.log.org.evosuite=off -Dorg.slf4j.simpleLogger.showLogName=true`
