### ISSUE TITLE
Regression from EvoCrash and small stacktrace

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/botsing#45]
#### Characteristics
- **Issue Type**: [bug/feature/test report]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [Botsing, 1.0.3]
- **Execution Environment**: [Linux]
- **Reporter**: [Mael, mael.audren@activeeon.com]

#### Description

By upgrading from EvoCrash to Botsing, I was not able to regenerate a test from a log that worked with EvoCrash. The stack trace is very small making it very hard to identify the issue. Is there way to increase the stack trace from Botsing ?

Here is the logs from Botsing:
```
Exception type is detected: org.objectweb.proactive.extensions.dataspaces.exceptions.SpaceNotFoundException
An error happened while generating a new output: For input string: "(Native Method"
```

#### Steps to reproduce

Clone https://github.com/stamp-project/botsing-gradle-plugin
Run `./gradlew shadowJar` in botsing-gradle-plugin root directory

Clone https://github.com/ow2-proactive/scheduling
Modify build.gradle to add botsing plugin dependency the configs (there is an example in botsing-gradle-plugin) :
```
botsing {
    libsPath="dist/lib/"
    targetFrame="1"
    logPath="PATH/SpaceNotFound.log"
}
```
Run in scheduling root directory:
```
./gradlew compileJava
./gradlew botsing
```

#### Other files and URLs

Log file : https://github.com/STAMP-project/evocrash-usecases-output/blob/master/Activeeon/Evocrash/scheduling/SpaceNotFoundException/SpaceNotFound.log

**Comment by pderakhshanfar** [comment]
Dear Mael,
You should remove any frame in stack trace which does not have any line number. According to the error message, one of the frames of the stack trace has string "Native Method" instead of a line number.

**Comment by MaelAudren** [comment]
Thanks it solved the issue. It seems with a better knowledge of Botsing, the stack trace is not that short.
