### ISSUE TITLE
Run Botsing for commons-collections4 or other example

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#46]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: botsing-reproduction 1.0.4-SNAPSHOT
- **Execution Environment**: Ubuntu 18.04
- **Reporter**: Luca Andreatta luca.andreatta@eng.it

#### Description
I need some working examples to see botsing-reproduction working as a standalone jar.

For this I need:
-     the log
-     the source code and the version
-     the command line to execute it as a standalone jar

For example I was trying with commons-collections-4.0 (taken from https://github.com/apache/commons-collections.git ) with ACC-474.log (I have found it somewhere in Evocrash examples), but I didn't find a way to run Botsing as a jar.

I tried with this:

java -jar ~/.m2/repository/eu/stamp-project/botsing-reproduction/1.0.4-SNAPSHOT/botsing-reproduction-1.0.4-SNAPSHOT.jar -crash_log ACC-474/ACC-474.log -target_frame 2 -project_cp /home/luca/Progetti/stamp/commons-collections/target/commons-collections4-4.0.jar:/home/luca/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/luca/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/luca/.m2/repository/org/easymock/easymock/3.2/easymock-3.2.jar:/home/luca/.m2/repository/cglib/cglib-nodep/2.2.2/cglib-nodep-2.2.2.jar:/home/luca/.m2/repository/org/objenesis/objenesis/1.3/objenesis-1.3.jar:/home/luca/.m2/repository/org/evosuite/evosuite-client/1.0.6/evosuite-client-1.0.6.jar

But I get some errors due to class path (doesn't find evosuite-client-1.0.6.jar?!?):

Exception in thread "main" java.lang.Error: Unresolved compilation problems:
    MODEL_PATH cannot be resolved or is not a field
    MODEL_PATH cannot be resolved or is not a field
    ALLOW_OBJECT_POOL_USAGE cannot be resolved or is not a field

    at eu.stamp.botsing.testgeneration.strategy.BotsingIndividualStrategy.generateTests(BotsingIndividualStrategy.java:86)
    at eu.stamp.botsing.reproduction.CrashReproduction.generateCrashReproductionTests(CrashReproduction.java:124)
    at eu.stamp.botsing.reproduction.CrashReproduction.execute(CrashReproduction.java:78)

**Comment by pderakhshanfar** [comment]
Dear Luca,
You did not package Botsing, properly. Some of the dependencies are not included. You should package Botsing according to the scripts that we put in [travis file](https://github.com/STAMP-project/botsing/blob/master/.travis.yml), or you can use the [latest release jar file](https://github.com/STAMP-project/botsing/releases).

**Comment by luandrea** [comment]
Ok, I tried to run Botsing using the jar created from the latest source code and I get that error.
I tried with the latest released and I get a different error:

```
10:23:59.918 [main] INFO  e.s.b.g.s.o.GuidedSearchUtility - Botsing found 1 Target call(s):
10:23:59.918 [main] INFO  e.s.b.g.s.o.GuidedSearchUtility - Target method #1 is putAll
10:23:59.922 [main] INFO  e.s.b.g.s.GuidedGeneticAlgorithm - Initializing the first population with size of 100 individuals
10:24:03.615 [main] ERROR e.s.b.f.t.f.RootMethodTestChromosomeFactory - Guided initialization failed. Please revise the target class and method!
10:24:03.615 [main] WARN  e.s.b.g.s.GuidedGeneticAlgorithm - Botsing was unsuccessful in generating the initial population. cause: Guided initialization failed. Please revise the target class and method!
```

**Comment by luandrea** [comment]
I succesfully run Botsing, but the resulting class has no tests:
`@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class ListOrderedMap_ESTest extends ListOrderedMap_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
`

Could you point me out some more useful example?

**Comment by pderakhshanfar** [comment]
We put some useful examples in the [Botsing demo repository](https://github.com/STAMP-project/botsing-demo).

**Comment by luandrea** [comment]
Hi Pouria, 
I successfully run botsing-reproduction 1.0.3 with the commons-lang3 example found in botsing-demo repository. It still doesn't work if I run it with botsing-reproduction 1.0.4, compiled from current source code. Plus I get an error because botsing-reproduction 1.0.4 (still current sources) is not compatible with evosuite-client-botsing-1.0.6.jar.

**Comment by pderakhshanfar** [comment]
Dear Luca,

I have added the building instruction to [README](https://github.com/STAMP-project/botsing/blob/master/README.md#building-botsing). You can use it to build the botsing-reproduction 1.0.4, properly.

**Comment by luandrea** [comment]
Hi Pouria,
I finally found that the problem is the library that I use to run botsing-reproduction in the commons-lang3 example.

In your [botsing-demo](https://github.com/STAMP-project/botsing-demo.git) I found this libraries:
* cglib-nodep-2.2.2.jar
* commons-io-2.4.jar
* commons-lang3-3.2-SNAPSHOT.jar
* commons-lang3-3.2-SNAPSHOT-tests.jar
* easymock-3.1.jar
* hamcrest-core-1.1.jar
* junit-4.10.jar
* objenesis-1.2.jar

But I started from (commons-lang)[https://github.com/apache/commons-lang] project on GitHub and checked out the LANG_3_2_RC1 tag (the one that was nearer to your example).
In the pom.xml I have found this other libraries ad dependencies (which are the same that botsing-maven now finds with the last update on (my repository)[https://github.com/luandrea/botsing]):
* commons-lang/target/classes
* commons-lang3-3.2.jar
* junit-4.11.jar
* hamcrest-core-1.3.jar
* commons-io-2.4.jar
* easymock-3.2.jar
* cglib-nodep-2.2.2.jar
* objenesis-1.3.jar

The result is that if I run botsing as a jar with your libraries it can generate the unit test, but using the LANG_3_2_RC1 libraries I get a NullpointerException on GuidedSearchUtility.getPublicCalls(GuidedSearchUtility.java:76).

I need your help to find an example (stacktrace, source code and how to execute botsing) to test my maven plugin.

**Comment by luandrea** [comment]
Hi Pouria,
I tried also the XWiki-7.4.2 example taken from the botsing-demo repository, but I couldn't generate a valid test. Could you help me?

I executed Botsing with this command:
`java -jar botsing-reproduction-1.0.3.jar -project_cp applications/XWIKI-7.4.2 -crash_log crashes/XWIKI-13196.log -target_frame 5 -Dsearch_budget=1200  -Dno_runtime_dependency=true`

**Comment by pderakhshanfar** [comment]
Try with other frame levels. For instance in this case if you run this command it will generate the test:
```
java -jar botsing-reproduction-1.0.3.jar -project_cp applications/XWIKI-7.4.2 -crash_log crashes/XWIKI-13196.log -target_frame 3 -Dsearch_budget=1200 -Dno_runtime_dependency=true
```
Botsing cannot replicate crash by targeting any frame in any stack trace. You should try with different target frames.

**Comment by luandrea** [comment]
Ok, I confirm that lowering the target frame to 4 the test case have been generated correctly.
I suggest to add also this command line in the README of botsing-demo, if it's possible.
