### ISSUE TITLE
config.properties file not found

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#48]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: always
- **Severity**: feature
- **Tool/Service/Component**: botsing-reproduction 1.0.4-SNAPSHOT
- **Execution Environment**: ALL
- **Reporter**: Luca Andreatta

#### Description

Executing Botsing from Maven plugin I get an error because it cannot find the properties file.

#### Steps to reproduce

Execute botsing-maven 1.0.4-SNAPSHOT, e.g.:

`mvn eu.stamp-project:botsing-maven:1.0.4-SNAPSHOT:botsing -Dcrash_log=LANG-9b.log -Dtarget_frame=2 -Dorg.slf4j.simpleLogger.log.org.evosuite=off -Dorg.slf4j.simpleLogger.showLogName=true`

#### Relationships

See also #6

**Comment by pderakhshanfar** [comment]
@luandrea  can you send the software log?

**Comment by luandrea** [comment]
Hi Pouria,
here is the stacktrace running botsing-maven on commons-lang3 example in verbose mode with Eclipse: 
[botsing-maven_on_commons-lang3.log](https://github.com/STAMP-project/botsing/files/2900114/botsing-maven_on_commons-lang3.log)

As a workaround I copied the properties file inside a folder (src/main/java/eu/stamp/botsing) in the commons-lang3 project itself (not a clean solution) as suggested by the code in eu.stamp.botsing.CrashProperties.loadConfig(CrashProperties.java:122-125):

```
String user_dir = System.getProperty("user.dir");
            Path configDir = Paths.get(user_dir, "src","main","java","eu","stamp","botsing","config.properties");
//            InputStream inputstream = getClass().getClassLoader().getResourceAsStream(configDir.toString());
            InputStream inputstream = new FileInputStream(configDir.toString());
```
