### ISSUE TITLE
Add developer documentation in README.md

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/botsing#5]
#### Characteristics
- **Issue Type**: feature
- **Severity**: feature
- **Tool/Service/Component**: botsing

#### Description

Add developer documentation in `README.md`.

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by luandrea** [comment]
It should be nice to have these things in the README:
* description of the project and modules
* how to install and run it with prerequisites
* how to compile and package it with prerequisites
* a tutorial or an example, maybe this could be in some other page and have here only a link to it
* link to the stamp site
* authors
* license note

You can take a look at what they have done in [DSPOT README](https://github.com/STAMP-project/dspot) or also in this [REAME template example](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2).

**Comment by xdevroey** [comment]
Duplicate with #15
