### ISSUE TITLE
NullPointerException on GuidedSearchUtility.getPublicCalls(GuidedSearchUtility.java:76)

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#55]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: botsing-reproduction 1.0.4-SNAPSHOT
- **Execution Environment**: Ubuntu 18.10
- **Reporter**: Luca Andreatta

#### Description

Trying to run botsing-reproduction 1.0.4-SNAPSHOT on commons-lang 3.2 source code with LANG-9b.log stacktrace gives NullPointerException on GuidedSearchUtility.getPublicCalls(GuidedSearchUtility.java:76).

This is useful find an example to run botsing-maven and have the same results starting from a maven project with source code.

#### Steps to reproduce
* git clone https://github.com/apache/commons-lang
* cd commons-lang
* git checkout LANG_3_2_RC1
* cp ..botsing-demo/crashes/LANG-9b.log . (from https://github.com/STAMP-project/botsing-demo.git)
* java -jar /home/luca/.m2/repository/eu/stamp-project/botsing-reproduction/1.0.4-SNAPSHOT/botsing-reproduction-1.0.4-SNAPSHOT.jar -project_cp lib-dependencies_botsing-maven/ -crash_log LANG-9b.log -target_frame 5 -Dsearch_budget=120

**Comment by pderakhshanfar** [comment]
This error happens when Botsing cannot find the target method in the given project_cp. Please check if project_cp set correctly.

**Comment by luandrea** [comment]
Ok, thank you Pouria. Maybe a more clear message would be better to understand the real problem.

What I need now is one or more maven project example to test the maven-botsing plugin and I need:

1. the source code
1. the stacktrace
1. the version 
1. the command to run botsing as a jar

I tried with:
1. commons-lang-3.2 from botsing-demo
    - I started from LANG_3_2_RC1 tag, but this is not the same as I can find in botsing-demo lib folder
1. XWIKI-7.4.2 from botsing-demo
    - I give up because there were too many modules (98) to build
1. ANT from EvoCrash experimental-case
    - [ANT-44689](http://www.evocrash.org/experimental-case-ant-44689.html) refers to ant-1.7 wich is built with Ant
1. commons-collection from EvoCrash experimental-case
    - [ACC-377](http://www.evocrash.org/experimental-case-acc-377.html) refers to version 3.2 which is built with Ant
1. log4j from EvoCrash experimental-case
    - [LOG-47912](http://www.evocrash.org/experimental-case-log-47912.html) is about an error on JULLog4jEventConverter which is not a class of log4j nor none of its dependencies

Could you help me to find a good test case?

I have done a pull request so you can have all the latest updates that I have done to botsing-maven and you can test it by yourself.

**Comment by pderakhshanfar** [comment]
You can find more crashes for apache commons lang, which is a maven project, [here](https://github.com/STAMP-project/JCrashPack/tree/master/crashes/Commons-lang). You can see the source code of the version that crash happened in it [here](https://github.com/STAMP-project/JCrashPack/tree/master/applications/Commons-lang).

About the cases that you tried:
1- commons-lang-3.2: you should check the classes which you built for the project to understand what is its difference with the jar file that we used in the demo. this case should work fine with the maven plugin too.
2- XWIKI-7.4.2: It should be a way for the maven plugin to tackle this problem. For instance, detecting and building a subset of modules which are related to the given stack trace.

**Comment by luandrea** [comment]
Ok, I tried with Commons-lang/LANG-13b in JCrashPack and found that the SRC is quite similar to commit 81797ed4402a982f90bd903c7437aeea4e3933f5 in https://github.com/apache/commons-lang.

But with botsing-reproduction-1.0.4-SNAPSHOT.jar the test case is null and with botsing-maven I get the Nullpointer on GuidedSearchUtility.

These are the steps for maven plugin:
* cd ~/Progetti/stamp
* git clone https://github.com/apache/commons-lang
* cd commons-lang
* git checkout 81797ed4402a982f90bd903c7437aeea4e3933f5
* wget https://raw.githubusercontent.com/STAMP-project/JCrashPack/master/crashes/Commons-lang/LANG-13b/LANG-13b.log
* mvn compile
* mvn eu.stamp-project:botsing-maven:1.0.4-SNAPSHOT:botsing -Dcrash_log=LANG-13b.log -Dtarget_frame=4 -Dorg.slf4j.simpleLogger.log.org.evosuite=off -Dorg.slf4j.simpleLogger.showLogName=true

These are the steps for botsing-reproduction.jar:
* cd ~/Progetti/stamp
* git clone https://github.com/apache/commons-lang
* cd commons-lang
* git checkout 81797ed4402a982f90bd903c7437aeea4e3933f5
* wget https://raw.githubusercontent.com/STAMP-project/JCrashPack/master/crashes/Commons-lang/LANG-13b/LANG-13b.log
* svn export https://github.com/STAMP-project/JCrashPack/trunk/applications/Commons-lang/13b/bin
* java -jar /home/luca/.m2/repository/eu/stamp-project/botsing-reproduction/1.0.4-SNAPSHOT/botsing-reproduction-1.0.4-SNAPSHOT.jar -project_cp bin/ -crash_log LANG-13b.log -target_frame 5 -Dsearch_budget=120

Can you try and let me know where is the problem?

**Comment by pderakhshanfar** [comment]
Can you send me the stack trace?

**Comment by luandrea** [comment]
I sent all the commands to reproduce it, did you try?

Here are the two executions log:
* [botsing-reproduction.log](https://github.com/STAMP-project/botsing/files/2941054/botsing-reproduction.log)
* [botsing-maven.log](https://github.com/STAMP-project/botsing/files/2941049/botsing-maven.log)

**Comment by pderakhshanfar** [comment]
I asked for a stack trace to answer you faster. I just looked at the log files that you sent to me, and now I have an answer for you.

 Botsing jar file could start and finish the search process. If you look at the `botsing-reproduction.log` file, that you sent to me, It mentioned that "The search process is finished". It did not save any test because it simply could not find the reproducing test in 2 minutes.

However, the problem that you have in the maven plugin is another problem. You have some stack traces there (similar to the stack trace that you mentioned it in the first comment). As I mentioned before, you are getting this error because you did not build and pass all of the required classes. I suggest you check your own code to make sure that all of the binary files that you are giving to botsing is similar to jar files which are pass as `project_cp` in `botsing-reproduction.log` execution.

**Comment by luandrea** [comment]
I tried to run botsing reproduction for 20 minutes, but the result is still an empty class.

**Comment by pderakhshanfar** [comment]
There is no guaranty for botsing to reproduce the example that you are using right now. If you want the reproduction, use the case that we put in Botsing-demo repo. (for instance LANG-9n frame 5). Botsing should achieve to fitness function 0.

**Comment by xdevroey** [comment]
I suggest you try with the [botsing-examples](https://github.com/STAMP-project/botsing/tree/master/botsing-examples) project. The stack traces are available [here](https://github.com/STAMP-project/botsing/tree/master/botsing-examples/src/main/resources). Those are the classes and stack traces that we use to test [botsing-reproduction main class](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/test/java/eu/stamp/botsing/BotsingTest.java) as well.
