### ISSUE TITLE
Native method in exception stack causes botsing to fail

### ISSUE THREAD

**Issue by gibello** [STAMP-project/botsing#57]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [Botsing, maven plugin]
- **Execution Environment**: [Linux Ubuntu 18.04]
- **Reporter**: [Pierre-Yves Gibello, pyg@ow2.org]

#### Description

When the exception stack contains a native method call, botsing fails.

#### Steps to reproduce

Exception stack sometimes contains lines like this one:
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Botsing fails with following error:
[ERROR] Failed to execute goal eu.stamp-project:botsing-maven:1.0.3:botsing (default-cli) on project authzforce-ce-core: Error executing Botsing: For input string: "(Native Method" -> [Help 1]
[...]
Caused by: java.lang.NumberFormatException: For input string: "(Native Method"

#### Other files and URLs

Attached exception stack (from authzforce OW2 project - https://gitlab.ow2.org/authzforce ), stored in /tmp/ex1 file, causes failure for mvn eu.stamp-project:botsing-maven:botsing -Dcrash_log=/tmp/ex1 -Dtarget_frame=2 -e
(launched in authzforce/core dir).

[ex1.log](https://github.com/STAMP-project/botsing/files/2952917/ex1.log)

**Comment by pderakhshanfar** [comment]
Thank you for opening this issue. We are working on this issue to resolve it for the next release. For now, you can remove the frames which do not contain the line number.

**Comment by xdevroey** [comment]
Hi @gibello, frames with `Native Method` and `Unknown Source` are not supported by botsing-reproduction right now. 

The reason is that we need the line numbers where the exception is thrown (or is propagated) in the frames to avoid being stuck with exceptions thrown at the wrong places during the search process. 

From a user perspective, you should remove those frames from the stack trace and rerun botsing with the cleaned up stack trace. @pasquy73 is writing a botsing-preprocessing utility to automate that process. See #9 for more details.

**Comment by gibello** [comment]
Ok. Got a code snippet that extracts exceptions from any log file (eg. a tomcat log file), and returns them as a list of String. If useful for you ?
Code follows...

```
    /**
     * Extract exceptions from a log stream (eg. an app server log file).
     * @param in The log stream (file or so) from which exceptions must be extracted.
     * @return A list of exceptions extracted in the input stream, null if none.
     * @throws IOException
     */
    public List<String> extractExceptions(BufferedReader in) throws IOException {
    	LinkedList<String> ret = null;   	
    	String line;
    	String previous = "";
    	Pattern pattern = Pattern.compile("(^\\tat |^Caused by: |^\\t... \\d+ more)");
    	Pattern nested = Pattern.compile("; nested exception is: *$");
    	StringBuffer currentException = null;
    	while((line = in.readLine()) != null) {
    		Matcher matcher = pattern.matcher(line);
    		if(matcher.find()) {
    			if(currentException == null) currentException = new StringBuffer(previous);
    			currentException.append("\n" + line);
    		} else if(currentException != null) {
    			Matcher nestedMatcher = nested.matcher(line);
    			if(nestedMatcher.find()) {
    				currentException.append("\n" + line);
    			} else {
    				if(ret == null) ret = new LinkedList<String>();
    				ret.add(currentException.toString().trim());
    				currentException = null;
    			}
    		}
    		previous = line;
    	}
    	return ret;
    }
```

**Comment by xdevroey** [comment]
This should be solved by the stack trace preprocessor in release [botsing-1.0.4](https://github.com/STAMP-project/botsing/releases/tag/botsing-1.0.4).

**Comment by gibello** [comment]
Fine, thanks. I also fixed my code (the snippet above) because it misses the last exception if EOF occurs within exception parsing. The regexp has also been modified, because logs don't always put tabs but sometimes blanks instead at the beginning of some exception stack lines (eg. tomcat logs do that).

Don't know if you use it or not, but new code follows:

```
    public List<String> extractExceptions(BufferedReader in) throws IOException {
    	LinkedList<String> ret = null;   	
    	String line;
    	String previous = "";
    	// Pattern more permissive than it could : should be ^\\t and never ^(\\t|\\s+)
    	// but required when exceptions are carelessly copied/pasted (with tabs replaced by spaces)
    	Pattern pattern = Pattern.compile("^(\\t|\\s+)at |^Caused by: |^(\\t|\\s+)... \\d+ more");
    	Pattern nested = Pattern.compile("; nested exception is: *$");
    	StringBuffer currentException = null;
    	while((line = in.readLine()) != null) {
    		Matcher matcher = pattern.matcher(line);
    		if(matcher.find()) {
    			if(currentException == null) currentException = new StringBuffer(previous);
    			currentException.append("\n" + line);
    		} else if(currentException != null) {
    			Matcher nestedMatcher = nested.matcher(line);
    			if(nestedMatcher.find()) {
    				currentException.append("\n" + line);
    			} else {
    				if(ret == null) ret = new LinkedList<String>();
    				ret.add(currentException.toString().trim());
    				currentException = null;
    			}
    		}
    		previous = line;
    	}
    	// Don't forget last exception if EOF at the midst of an exception stack
    	if(currentException != null) {
			if(ret == null) ret = new LinkedList<String>();
			ret.add(currentException.toString().trim());
    	}
    	return ret;
    }
```
