### ISSUE TITLE
config.properties should be configurable and optional

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#6]
#### Characteristics
- **Issue Type**: feature

#### Description

botsing should not rely on a config file inside a fixed folder, but this should be outside of it and configurable. And maybe optional.

Example: 
https://github.com/STAMP-project/botsing/blob/bb093a838fdaf28865a945fad11d9f95e136352f/botsing-reproduction/src/main/java/eu/stamp/botsing/CrashProperties.java#L99

**Comment by pderakhshanfar** [comment]
Hi @luandrea 
The parameters which passed in the config file can be set by Command Line too. The CLI parameters override those in the config file.

**Comment by luandrea** [comment]
Hi @pderakhshanfar,
I will check that and let you know if I have problems. 

What about the reference to the config file?
