### ISSUE TITLE
botsing-preprocessing doc error and missing download

### ISSUE THREAD

**Issue by gibello** [STAMP-project/botsing#62]
#### Characteristics
- **Issue Type**: [documentation]
- **Severity**: [minor]
- **Reporter**: [Pierre-Yves Gibello, pyg@ow2.org]

#### Description

In the botsing-preprocessing doc (README.md), at least 2 issues:
- The link to botsing release points to a place where there is no botsing-preprocessing jar.
- The command line options are wrong: it is -l instead of -i, and there is no "=" sign after options (but a space, as usual).

**Comment by pasquy73** [comment]
Please refer to this [doc](https://github.com/STAMP-project/botsing#botsing-preprocessing)

**Comment by gibello** [comment]
It's what I did. No botsing-preprocessing jar in the releases, and wrong option for the command line.

**Comment by xdevroey** [comment]
I made a release with the latest version of the preprocessing tool (see https://github.com/STAMP-project/botsing/releases/tag/botsing-1.0.4). @pasquy73 can you fix the documentation and move it to the [Command line interface](https://github.com/STAMP-project/botsing#command-line-interface) section. Right now it is in the [Contributing](https://github.com/STAMP-project/botsing#contributing) section, which is wrong.

**Comment by xdevroey** [comment]
Fixed in #65
