### ISSUE TITLE
Prepare a new release of Botsing with preprocessing, model generation and crash reproduction command line tools

### ISSUE THREAD

**Issue by pasquy73** [STAMP-project/botsing#64]
#### Characteristics
- **Issue Type**: [feature]
- **Tool**: [botsing]

#### Description
The botsing preprocessing task is completed. It could be useful to integrate it in the botsing.

**Comment by xdevroey** [comment]
Hi @pasquy73, I will prepare a release with the different command line tools for the Stockholm meeting.

**Comment by xdevroey** [comment]
Done, available at https://github.com/STAMP-project/botsing/releases/tag/botsing-1.0.4
