### ISSUE TITLE
Issue while building Botsing

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/botsing#69]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [Botsing, v1.0.4, Commit 7fad258b430d6c2c4476b6c6eb49bd9a43bd3288 (currently master HEAD)]
- **Execution Environment**: [Ubuntu, 18.0.4]
- **Reporter**: [Mael Audren, mael.audren@activeeon.com]

#### Description

I've not managed to build Botsing following the documentation.

I've followed the documentation (Build Botsing paragraph) to build Botsing and I've run the following command:
`mvn install:install-file -Dfile=botsing-reproduction/evosuite-client-botsing-1.0.7.jar -DgroupId=org.evosuite -DartifactId=evosuite-client-botsing -Dversion=1.0.7 -Dpackaging=jar`

The output is `Erreur : impossible de trouver ou charger la classe principale org.codehaus.plexus.classworlds.launcher.Launcher`
In English `Error : Impossible to load main class org.codehaus.plexus.classworlds.launcher.Launcher`
 
#### Steps to reproduce
1/ Clone Botsing
2/ Run `mvn install:install-file -Dfile=botsing-reproduction/evosuite-client-botsing-1.0.7.jar -DgroupId=org.evosuite -DartifactId=evosuite-client-botsing -Dversion=1.0.7 -Dpackaging=jar`

**Comment by MaelAudren** [comment]
I've discovered the same issue for the module botsing-maven.

**Comment by xdevroey** [comment]
Hi @MaelAudren, it is working fine on my setup:
```
Apache Maven 3.5.2 
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
```
Could you check your Maven installation with `mvn -version`?

**Comment by MaelAudren** [comment]
Thanks Xavier, it seems that the issue comes from my environment and is not linked to Botsing.

**Comment by MaelAudren** [comment]
I updated maven and it fixed the issue.
