### ISSUE TITLE
botsing should be configurable programmatically

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#7]
#### Characteristics
- **Issue Type**: feature

#### Description

botsing should be configurable programmatically. I didn't find a way to pass different parameters to Botsing except crash_log, target_frame and projectCP.

Take a look at: 
https://github.com/STAMP-project/botsing/blob/bb093a838fdaf28865a945fad11d9f95e136352f/botsing-reproduction/src/main/java/eu/stamp/botsing/CrashProperties.java#L152

**Comment by pderakhshanfar** [comment]
@luandrea check my answer for issue #6
