### ISSUE TITLE
Cannot generate test with botsing-examples project

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing#70]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: botsing-reproduction 1.0.5-SNAPSHOT
- **Execution Environment**: Ubuntu 18.10
- **Reporter**: luca.andreatta@eng.it

#### Description

I tryed to run botsing-reproduction on botsing-examples example, but the generated class has an empty test.

#### Steps to reproduce

```
cd /tmp
mkdir stamp-test
cd stamp-test/
git clone https://github.com/STAMP-project/botsing.git
mvn install:install-file -Dfile=botsing-reproduction/evosuite-client-botsing-1.0.7.jar -DgroupId=org.evosuite -DartifactId=evosuite-client-botsing -Dversion=1.0.7 -Dpackaging=jar
mvn install -DskipTests
cd botsing/botsing-examples
mvn package
mkdir bin
cp target/botsing-examples-1.0.5-SNAPSHOT.jar bin/
cp ~/.m2/repository/junit/junit/4.12/junit-4.12.jar bin/
cp ~/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar bin/
cp ~/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar bin/
java -jar ~/.m2/repository/eu/stamp-project/botsing-reproduction/1.0.5-SNAPSHOT/botsing-reproduction-1.0.5-SNAPSHOT.jar -project_cp bin/ -crash_log src/main/resources/Fraction.log -target_frame 1
```

**Comment by xdevroey** [comment]
There seems to be a problem during the minimization process when `no_runtime_dependency` is set to true (which is the default value). The following command generates a non-empty test:
```
java -jar botsing-reproduction-1.0.4.jar -project_cp bin/ -crash_log src/main/resources/Fraction.log -target_frame 1 -Dno_runtime_dependency=false
```
I will set the default value of `no_runtime_dependency` to false.

**Comment by luandrea** [comment]
Hi Xavier, I tried to add this parameter also to botsing-maven to have a running example, but it didn't work.
I passed to botsing in the properties it as  "-Dno_runtime_dependency=false", but it didn't work.

In the log I see this:

```
[ERROR] org.evosuite.junit.JUnitAnalyzer - Failed to compile test case:
Fraction fraction0 = new Fraction((-1), (-1));
fraction0.getShiftedValue(1);
[INFO] org.evosuite.junit.JUnitAnalyzer - Going to execute: handleTestsThatAreUnstable
[INFO] eu.stamp.botsing.reproduction.CrashReproduction - * Writing JUnit test case 'Fraction_ESTest' to crash-reproduction-tests
[INFO] eu.stamp.botsing.reproduction.CrashReproduction - The solution test is saved!
```

What does it mean?

**Comment by xdevroey** [comment]
Hi @luandrea, there was a missing dependency to `evosuite-standalone-runtime` (since we turned the `no_runtime_dependency` option to false) I have added it. From my test, there seems still to be a problem with the writing of the test cases when using the Maven plugin but I have no idea where it comes from. Can you look into this?

**Comment by luandrea** [comment]
Hi @xdevroey, 
from what I see the problem arise in org.evosuite.junit.JUnitAnalyzer as some evosuite libraries is missing:

`[ERROR] org.evosuite.junit.JUnitAnalyzer - Diagnostic: package org.evosuite.runtime does not exist: 10`

Here is the complete log: 
[botsing-maven_on_pdp-engine.log](https://github.com/STAMP-project/botsing/files/3023031/botsing-maven_on_pdp-engine.log)

I executed this command from pdp-engine, a module of authzforce, to run botsing-maven (compiled with your last commit with evosuite-standalone-runtime):

`mvn eu.stamp-project:botsing-maven:1.0.5-SNAPSHOT:botsing -Dcrash_log=crash.log -Dtarget_frame=1 -Dno_runtime_dependency=false -Dorg.slf4j.simpleLogger.log.org.evosuite=error -Dorg.slf4j.simpleLogger.showLogName=true`

**Comment by luandrea** [comment]
Just to try, I added evosuite-standalone-runtime to the pdp-engine but I got this error:

```
[INFO] eu.stamp.botsing.reproduction.CrashReproduction - * Compiling and checking tests
[ERROR] org.evosuite.runtime.classhandling.ClassStateSupport - Class net.sf.saxon.expr.instruct.Doctype was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[ERROR] org.evosuite.runtime.classhandling.ClassStateSupport - Class net.sf.saxon.s9api.XsltCompiler was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
....
[ERROR] org.evosuite.runtime.classhandling.ClassStateSupport - Class net.sf.saxon.functions.AccumulatorFn$AccumulatorBefore was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[INFO] eu.stamp.botsing.reproduction.CrashReproduction - * Writing JUnit test case 'SchemaHandler_ESTest' to crash-reproduction-tests
[INFO] eu.stamp.botsing.reproduction.CrashReproduction - The solution test is saved!
```

I got an empty test again, but if it worked I could add evosuite-standalone-runtime to the classpath in the mojo. What do you think?

**Comment by luandrea** [comment]
Also the package org.evosuite.runtime is already inside botsing-reproduction that is a dependency declared in the pom.xml of the botsing-maven module.

**Comment by luandrea** [comment]
I tried to run botsing-maven with the parameter -Dno_runtime_dependency=true, the test generated is stil empty but I didn't get any exception in the minimization process.
What does it do the no_runtime_dependency? 
Is there a way to exclude the minimization process?

**Comment by xdevroey** [comment]
`no_runtime_dependency ` tells the EvoSuite test case generator used by Botsing to generate plain JUnit test cases. Otherwise, EvoSuite generates test cases with its own running environment that tries to avoid flakiness (by fixing the seed for random generators, handling input and outputs, etc.). See the **How to run the generated JUnit tests** section from [EvoSuite documentation](http://www.evosuite.org/documentation/commandline/).

The behavior you describe is strange. When I set the option `-Dno_runtime_dependency=false` with `botsing-reproduction`, the test is generated. Also, the option is set to false by default in `bosting-reproduction` so it should be fine with the Maven plugin too.

>Is there a way to exclude the minimization process?
No, otherwise the generated test would be too long.

**Comment by luandrea** [comment]
I changed completely how botsing-maven call botsing-reproduction, and now I'm able to generate the reproduction test with the botsing-example code.
