### ISSUE TITLE
Support Botsing preprocessor within Botsing Maven plugin

### ISSUE THREAD

**Issue by danzone** [STAMP-project/botsing#74]
#### Characteristics
- **Issue Type**: feature
- **Tool/Service/Component**: Botsing, 1.0.4
- **Execution Environment**: Maven 3.5.x

#### Description
Extend Botsing Maven plugin to support Botsing pre-processor 

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by xdevroey** [comment]
Implemented in botsing-1.0.6. See release https://github.com/STAMP-project/botsing/tree/botsing-1.0.6
