### ISSUE TITLE
The default value of Botsing crash reproduction version is hard-coded in the maven plugin source code

### ISSUE THREAD

**Issue by pderakhshanfar** [STAMP-project/botsing#76]
#### Characteristics
- **Reproducibility**: always
- **Tool/Service/Component**: Maven Plugin

#### Description
Botsing version default value is hard-coded in the [BotsingMojo](https://github.com/STAMP-project/botsing/blob/03cd33fbce99d4b120fa7ad8150ddd4c5f8e5ef0/botsing-maven/src/main/java/eu/stamp/botsing/BotsingMojo.java#L97). So, it should be changed before any release.

**Comment by luandrea** [comment]
SNAPSHOT version has been removed in botsing-maven 1.0.6-SNAPSHOT thanks to the release of 1.0.5 version of botsing modules.
