### ISSUE TITLE
Botsing command syntax

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/botsing#8]
#### Characteristics
- **Issue Type**:  question
- **Severity**:  question
- **Tool/Service/Component**: Botsing
- **Execution Environment**: Linux, Windows
- **Reporter**: Ricardo Tejada <ricardo.tejada.external@atos.net>

#### Description

I would like to give the parameters of the config.properties to Botsing using the command line,
botsing.parseCommandLine(command) as in the example.

But I'm not sure about the syntax.

Thank you.

**Comment by pderakhshanfar** [comment]
Hi @RicardoTej 
For passing any option, which is already available in the config file, with parseCommandLine, you need to give it as one of the elements of the input array with this format: `-D[property name]=[property value]`

For instance, if you want to change the directory of the generated test, you should pass: `"-Dtest_dir=[directory]"`

**Comment by RicardoTej** [comment]
Thank you @pderakhshanfar 

I will tell you if I find any problem

**Comment by RicardoTej** [comment]
Now it works fine and it generates the tests,

but at the begin it produces this trace asking for the properties file
(it doesn't stop and it generates the tests)

![botsingtrace](https://user-images.githubusercontent.com/36235771/46211444-13e75700-c323-11e8-8d91-7674990bcf8c.png)

I'm using this command

![botsingparameters](https://user-images.githubusercontent.com/36235771/46212289-2498cc80-c325-11e8-9cd7-aed2f6ac4e24.png)

Am I doing something wrong ?

Thank you.

**Comment by pderakhshanfar** [comment]
I think you completely removed the config file and it can not find it. Currently, we just handled these kinds of exceptions by printing the stack trace. However, I should replace it with a representative error message in the future. In general, the config file is used for passing the default values that we are not going to change them in most of our runs. It should be there, even if it is empty.

**Comment by RicardoTej** [comment]
Yes, I removed it, then I will put it again.
Tahnk you.
