### ISSUE TITLE
Failing Test in botsing-reproduction

### ISSUE THREAD

**Issue by pasquy73** [STAMP-project/botsing#82]
#### Characteristics
- **Issue Type**: [bug]
- **Severity**: [minor]
- **Execution Environment**: [Win]
- **Reporter**: [name, mail]

#### Description
The test case (CrashPropertiesTest.java) in botsing-reproduction provides an error when I try to run (mvn install) in Win7:
```
testSetClasspath(eu.stamp.botsing.CrashPropertiesTest)  Time elapsed: 0.002 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<jar1[]> but was:<jar1[:jar2]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at eu.stamp.botsing.CrashPropertiesTest.testSetClasspath(CrashPropertiesTest.java:71)
...
```

**Comment by pasquy73** [comment]
I solved this error! I used File.pathSeparator in the properties.setClasspath instead of slash (:).

**Comment by pasquy73** [comment]
I committed in the "pasquale" branch (https://github.com/STAMP-project/botsing/tree/pasquale)

**Comment by xdevroey** [comment]
Ok, thanks! Let us know when you do a pull request with those changes.
