### ISSUE TITLE
EvoSuite sandbox (Security Manager) seems not to be disabled (by -Dsandbox=False) in EvoSuite execution

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/botsing#92]
#### Characteristics
- **Issue Type**: Test report
- **Reproducibility**: Always
- **Severity**: Major
- **Tool/Service/Component**: EvoSuite 1.0.7
- **Execution Environment**: Centos 7
- **Reporter**: Jesús Gorroñogotia <jesus.gorronogoitia@atos.net>

#### Description
I've executed EvoSuite for test generation on Atos Supersede IF, using the script described below, in order to disable the security restrictions, but EvoSuite reports:

```
* Permissions denied during test execution: 
  - java.io.FilePermission: 
         write /dev/random: 1
  - javax.net.ssl.SSLPermission: 
         setHostnameVerifier: 2
```
So, it just generates a trivial test case, but not any usable one, because all IF test relies on network communications.

Am I doing something wrong?

#### Steps to reproduce
This is the script I am using to run EvoSuite:
```
java -d64 -Xmx4000m -jar supersede-if-botsing/evosuite-master-1.0.7-SNAPSHOT.jar \
	-class "eu.supersede.integration.api.security.test.IFAuthenticationManagerTest" \
	-projectCP "$(cat results/classpath.txt)" \
	-generateMOSuite \
	-Dalgorithm=DynaMOSA \
	-Dsearch_budget=60 \
	-Dseed_clone="0.5" \
	-Donline_model_seeding=TRUE \
	-Dmodel_path="results/models" \
	-Dtest_dir="results/evosuite-tests" \
	-Dreport_dir="results/evosuite-report" \
	-Dno_runtime_dependency=true
	-Dsandbox=False
```

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by pderakhshanfar** [comment]
@jesus-gorronogoitia, `-Dsandbox=false` should remove most restrictions for test generation, including file and SSL permissions. However, it seems that, in your case, EvoSuite still does not permit your software. The only way that we can understand the problem is debugging EvoSuite while it is running on your software. We can try to understand the issue on Monday.

**Comment by jesus-gorronogoitia** [comment]
Thanks @Pouria, let's do it on Monday. What do you need for debugging? I ask because I am running EvoSuite within a Docker container that only contains the JDK, Botsing/Evosuite libraries and Atos IF project, no any development tool/IDE

**Comment by pderakhshanfar** [comment]
We need an IDE for monitoring the execution traces and variable values. Otherwise, I think we cannot understand what is happening in the code.

**Comment by jesus-gorronogoitia** [comment]
Hi @Pouria, what IDE do you need? Eclipse would work?

**Comment by pderakhshanfar** [comment]
Personally, I prefer the free version of IntelliJ. However, I can work with Eclipse as well.

**Comment by jesus-gorronogoitia** [comment]
Ok, I will try to install IntelliJ in the container to see if I can make it work.

**Comment by xdevroey** [comment]
There was a missing '\' in the command. The right command is 
```
java -d64 -Xmx4000m -jar supersede-if-botsing/evosuite-master-1.0.7-SNAPSHOT.jar \
	-class "eu.supersede.integration.api.security.test.IFAuthenticationManagerTest" \
	-projectCP "$(cat results/classpath.txt)" \
	-generateMOSuite \
	-Dalgorithm=DynaMOSA \
	-Dsearch_budget=60 \
	-Dseed_clone="0.5" \
	-Donline_model_seeding=TRUE \
	-Dmodel_path="results/models" \
	-Dtest_dir="results/evosuite-tests" \
	-Dreport_dir="results/evosuite-report" \
	-Dno_runtime_dependency=true \
	-Dsandbox=False
```
